necysc/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path("", include("necysc_app.urls")),
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('images/favicon.ico'))),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
]

necysc_app/urls.py
from django.urls import path

from . import views

app_name = "necysc_app"
urlpatterns = [
    # Website Pages
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("programs/", views.programs, name="programs"),
    path("staff/", views.staff, name="staff"),
    path("faq/", views.faq, name="faq"),
    path("registration/", views.registration, name="registration"),
    path("logout/", views.logout_view, name="logout"),
    path("registrationinfo/", views.registrationinfo, name="registrationinfo"),
    # Applicant Portal Pages
    path("applicant/login/", views.login, name="login"),
    path("applicant/register/", views.register, name="register"),
    path("applicant/", views.home, name="home"),
    path("applicant/new_application/",
         views.new_application, name="new_application"),
    path("applicant/submit_application/",
         views.submit_application, name="submit_application"),
    path("applicant/application_review/<int:application_id>/",
         views.application_detail, name="application_detail"),
    path("applicant/edit_application/<int:application_id>/",
         views.edit_application, name="edit_application"),
]

necysc_app/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms
from django.contrib.auth.models import User
from .models import Applicant

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class CreateAuthenticationForm(AuthenticationForm):    
    class Meta:
        model = User
        fields = ['username', 'password']

class ApplicationForm(forms.ModelForm):
    class Meta:
        model = Applicant
        fields = [# camper info
                  'applicant_fname', 'applicant_lname', 'applicant_chinese_name', 'applicant_email',
                  'applicant_bday', 'applicant_sex', 'applicant_grade', 'applicant_shirt_size', 
                  'program', 
                  'street_address', 'city', 'state', 'zip_code',

                  # parent/guardian/emergency contact info
                  'parent1_fname', 'parent1_lname', 'parent1_relationship', 'parent1_phone', 'parent1_email', 'parent1_for_POD',
                  'parent2_fname', 'parent2_lname', 'parent2_relationship', 'parent2_phone', 'parent2_email', 'parent2_for_POD',
                  'additional_emergency_contact_fname', 'additional_emergency_contact_lname', 'additional_emergency_contact_relationship', 'additional_emergency_contact_phone',

                  # POD preference
                  'interest_in_POD_lead',

                  # roommate requests
                  'preferred_roommate',

                  # medical info
                  'insurance_provider', 'subscriber_name', 'primary_physician_name', 'primary_physician_phone',
                  'grant_hospital_permission', 'grant_medical_treatment_permission', 'grant_first_aid_permission', 'grant_meds_permission', 'grant_bug_spray_permission', 'grant_skin_treatment_permission',
                  'allergies', 'allergies_description', 'initial_for_allergy_treatment', 'epi_pen_prescribed',
                  'social_emotional_concerns',
                  'wear_glasses', 'wear_contacts', 'wear_hearing_aids',
                  'medication', 'medication_description', 
                  'opt_out_activities', 'medical_comments',
                  'signature',

                  # pickup info
                  'allowed_pickup_persons', 'available_for_carpool', 

                  # payment info
                  'payment_camp', 'payment_pod', 'payment_donation', 'payment_total', 'financial_aid_requested',
                  
                  # additional info
                  'listing_on_weekbook', 'camper_contact_email', 
                  'interest_in_committee', 'interest_in_wkbook_ads',
                  'referrals', 'heard_from',
                
                  # important docs
                  'camp_rule_agreement', 'liability_agreement',
                  ]

necysc_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from .models import Applicant, GlobalData
from .forms import CreateAuthenticationForm, CreateUserForm, ApplicationForm
from django.contrib.auth import login as auth_login, authenticate, logout
from django.contrib.auth.decorators import login_required

# Website Pages


def index(request):
    context = {}
    return render(request, 'necysc_app/website/index.html', context)


def about(request):
    context = {}
    return render(request, 'necysc_app/website/about.html', context)


def programs(request):
    context = {}
    return render(request, 'necysc_app/website/programs.html', context)


def staff(request):
    context = {}
    globaldata = GlobalData.get_solo()
    context = {
        "globaldata": globaldata,
    }
    print(globaldata)
    return render(request, 'necysc_app/website/staff.html', context)


def registration(request):
    context = {}
    return render(request, 'necysc_app/website/registration.html', context)


def faq(request):
    context = {}
    return render(request, 'necysc_app/website/faq.html', context)


def registrationinfo(request):
    context = {}
    return render(request, 'necysc_app/website/registration.html', context)

# Applicant Portal


def login(request):
    # check if user is already logged in
    if request.user.is_authenticated:
        return redirect('necysc_app:home')
    if request.method == 'POST':
        form = CreateAuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                auth_login(request, user)
                return redirect('necysc_app:home')
    else:
        form = CreateAuthenticationForm()
    context = {'form': form}
    return render(request, 'necysc_app/applicant/login.html', context)


def register(request):
    # check if user is already logged in
    if request.user.is_authenticated:
        return redirect('necysc_app:home')

    form = CreateUserForm()
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password1')
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            # fix
            return redirect('necysc_app:login')
    context = {'form': form}
    return render(request, 'necysc_app/applicant/register.html', context)


@login_required
def logout_view(request):
    logout(request)
    return redirect('necysc_app:index')


@login_required
def home(request):
    applications = Applicant.objects.filter(user=request.user)

    context = {'applications': applications}
    return render(request, 'necysc_app/applicant/index.html', context)

# show each application


@login_required
def application_detail(request, application_id):
    application = Applicant.objects.get(id=application_id)
    context = {'application': application}
    if application.user == request.user:
        return render(request, 'necysc_app/applicant/application_detail.html', context)
    else:
        return redirect('necysc_app:home')


@login_required
def edit_application(request, application_id):
    application = Applicant.objects.get(id=application_id, user=request.user)
    if not application.user == request.user:
        return redirect('necysc_app:home')
    if request.method == 'POST':
        form = ApplicationForm(request.POST, instance=application)
        if form.is_valid():
            form.save()
            return redirect('necysc_app:application_detail', application_id=application.id)
    else:
        form = ApplicationForm(instance=application)
    context = {'form': form, 'application': application}
    return render(request, 'necysc_app/applicant/edit_application.html', context)


@login_required
def new_application(request):
    form = ApplicationForm()

    globaldata = GlobalData.get_solo()

    context = {
        "form": form,
        "globaldata": globaldata,
    }
    return render(request, 'necysc_app/applicant/new_application.html', context)


@login_required
def submit_application(request):
    if request.method == 'POST':
        form = ApplicationForm(request.POST)
        if form.is_valid():
            # Create instance but don't save yet
            application = form.save(commit=False)
            # check if application exists
            application.user = request.user        # Assign the current user
            application.save()                     # Now save the instance
            form.save()
            return redirect('necysc_app:home')
    else:
        redirect('necysc_app:new_application')
    context = {"form": form}
    return render(request, 'necysc_app/applicant/submit_application.html', context)

necysc_app/templates/necysc_app/applicant/application_detail.html
{% extends "necysc_app/base.html" %}
{% load static %}

{% block title %} Application Details {% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'necysc_app/application_detail.css' %}">

<div>
    <a href="{% url 'necysc_app:home' %}" class="btn-purple rounded-pill">Back to Home</a>
</div>
<div class="application-detail">
    <div class="application-detail-header">
        <h2>Name: {{ application.applicant_fname }} {{ application.applicant_lname }}</h2>
        <a href="{% url 'necysc_app:edit_application' application.id %}" class="btn-purple">Edit Application</a>
    </div>

    {% if application.applicant_chinese_name %}
        <h3>Chinese Name: {{ application.applicant_chinese_name }}</h3>
    {% endif %}
    <p>Email: {{ application.applicant_email }}</p>
    <p>Birthday: {{ application.applicant_bday }}</p>
    <p>Sex: {{ application.applicant_sex }}</p>
    <p>Grade: {{ application.applicant_grade }}</p>
    <p>Shirt Size: {{ application.applicant_shirt_size }}</p>
    <p>Program: {{ application.program }}</p>
    <p>Address: {{ application.street_address }}, {{ application.city }}, {{ application.state }} {{ application.zip_code }}</p>
    
    <h3 class="section-title">Parent/Guardian Information</h3>
    <p>Parent 1: {{ application.parent1_fname }} {{ application.parent1_lname }} ({{ application.parent1_relationship }})</p>
    <p>Phone: {{ application.parent1_phone }}</p>
    <p>Email: {{ application.parent1_email }}</p>
    <p>Parent 2: {{ application.parent2_fname }} {{ application.parent2_lname }} ({{ application.parent2_relationship }})</p>
    <p>Phone: {{ application.parent2_phone }}</p>
    <p>Email: {{ application.parent2_email }}</p>
    
    <h3 class="section-title">Emergency Contact</h3>
    <p>Phone: {{ application.additional_emergency_contact_phone }}</p>
    
    <h3 class="section-title">Medical Information</h3>
    <p>Insurance Provider: {{ application.insurance_provider }}</p>
    <p>Subscriber Name: {{ application.subscriber_name }}</p>
    <p>Primary Physician: {{ application.primary_physician_name }}</p>
    <p>Phone: {{ application.primary_physician_phone }}</p>
    <p>Allergies: {{ application.allergies }}</p>
    <p>Allergies Description: {{ application.allergies_description }}</p>
    <p>Medications: {{ application.medication }}</p>
    <p>Medications Description: {{ application.medication_description }}</p>
    
    <h3 class="section-title permissions">Permissions</h3>
    <p>Grant Hospital Permission: {{ application.grant_hospital_permission }}</p>
    <p>Grant Medical Treatment Permission: {{ application.grant_medical_treatment_permission }}</p>
    <p>Grant First Aid Permission: {{ application.grant_first_aid_permission }}</p>
    <p>Grant Meds Permission: {{ application.grant_meds_permission }}</p>
    <p>Grant Bug Spray Permission: {{ application.grant_bug_spray_permission }}</p>
    <p>Grant Skin Treatment Permission: {{ application.grant_skin_treatment_permission }}</p>
    
    <h3 class="section-title">Additional Information</h3>
    <p>Signature: {{ application.signature }}</p>
    <p>Allowed Pickup Persons: {{ application.allowed_pickup_persons }}</p>
    <p>Available for Carpool: {{ application.available_for_carpool }}</p>
    <p>Payment Camp: {{ application.payment_camp }}</p>
    <p>Payment POD: {{ application.payment_pod }}</p>
    <p>Payment Donation: {{ application.payment_donation }}</p>
    <p>Payment Total: {{ application.payment_total }}</p>
    <p>Financial Aid Requested: {{ application.financial_aid_requested }}</p>
    <p>Listing on Weekbook: {{ application.listing_on_weekbook }}</p>
    <p>Camper Contact Email: {{ application.camper_contact_email }}</p>
    <p>Interest in Committee: {{ application.interest_in_committee }}</p>
    <p>Interest in Weekbook Ads: {{ application.interest_in_wkbook_ads }}</p>
    <p>Referrals: {{ application.referrals }}</p>
    <p>Heard From: {{ application.heard_from }}</p>
    <p>Camp Rule Agreement: {{ application.camp_rule_agreement }}</p>
    <p>Liability Agreement: {{ application.liability_agreement }}</p>
</div>
{% endblock %}

necysc_app/templates/necysc_app/applicant/application_status.html
{% extends "necysc_app/base.html" %} 

{% block title %} Applicant Status {% endblock %} 

{% block content %}
<h1>This applications status</h1>

{% endblock %}

necysc_app/templates/necysc_app/applicant/index.html
{% extends "necysc_app/base.html" %}
{% load static %}
{% block title %} Applicant Portal {% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'necysc_app/applicant_home.css' %}">

<style>
    body {
        background-color: #f8f9fa;
        margin: 0;
        padding: 0;
        height: 100%;
        width: 100%;
        position: relative;
    }
    
    .background {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: calc(100% - 0px);
        z-index: -1;
        background-image: url("{% static 'necysc_app/images/necyscbannerimage.jpg' %}");
        background-size: cover;
        background-position: center;
        filter: blur(8px); 
    }

    body, html {
        margin: 0;
        padding: 0;
        height: 100%;
        width: 100%;
        background-color: #f8f9fa; /* 可选 */
    }

    .container {
        position: relative;
        z-index: 1; 
        background-color: rgba(255, 255, 255, 0.9); 
        padding: 20px;
        border-radius: 10px;
        max-width: 1200px;
        margin: auto;
        margin-top: 20px;
    }

    h1, p, a, button {
        position: relative;
        z-index: 2;
    }

    .button-container {
        display: flex;
        justify-content: center;
        align-items: flex-start; 
        margin-top: 5vh;
        margin-bottom: 5vh;
    }
    .content-container {
        display: flex;
        flex-direction: column; 
        justify-content: center; 
        align-items: center;
        height: 13vh; 
        margin-top: 5vh; 
    }

    .btn-purple {
        background-color: #4e598c;
        color: #f9c784;
        transition: all 0.3s ease;
        border: none;
        padding: 15px 30px; 
        cursor: pointer;
        font-size: 18px; 
        border-radius: 50px;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.2); 
    }

    .welcome-title {
        font-size: 10vh; 
        text-align: center; 
        margin-bottom: 20px; 
        font-weight: bold;
        text-shadow: 2px 2px 5px rgba(0, 0, 0, 0.2); 
    }

    .btn-purple:hover {
        background-color: #f9c784;
        color: #ffffff;
    }

    .enlarged-btn {
        transform: scale(1);
        transition: transform 0.3s ease;
    }

    .enlarged-btn:hover {
        transform: scale(1.2); 
    }
</style>

<div class="background"></div>


<div class="content-container">
    <h2 class="welcome-title">Welcome!</h2>
</div>

{% if applications %}
<div class="container mb-4">
    {% for application in applications %}
    <div class="card col-md-6 glow">
        <a href="{% url 'necysc_app:application_detail' application.id %}" class="application-card-link">
            <div class="card-body">
                <div class="d-flex justify-content-between align-items-center row pe-4">
                    <h5 class="card-title col-md-8">
                        <span>{{ application.applicant_fname }} {{ application.applicant_lname }}</span>                                                 
                    </h5>
                    <h5 class="card-title col-md-4 float-end">
                        {% if application.app_status == 'A' %}
                        <span class="badge bg-success">Accepted</span>
                        {% elif application.app_status == 'I' %}
                        <span class="badge bg-secondary">Pending</span>
                        {% elif application.app_status == 'R' %}
                        <span class="badge bg-danger">Rejected</span>
                        {% else %}
                        <span class="badge bg-warning">Incomplete</span>
                        {% endif %}
                    </h5>
                </div>
                <hr>
                <p class="card-text fw-light">Year: {{ application.app_year }}</p>
                <p class="card-text m-0 fw-light">Health Status: {{ application.health_record_status }}</p>
            </div>
        </a>
    </div>
    {% endfor %}
</div>
{% endif %}

<div class="button-container">
    <a class="btn-purple enlarged-btn" href="{% url 'necysc_app:new_application' %}">Create new camper application</a>
</div>
{% endblock %}

necysc_app/templates/necysc_app/applicant/login.html
{% extends "necysc_app/base.html" %} {% load static %} {% block title %} Login /
Register {% endblock %} {% block content %}

<style>
    .login_page {
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: row;
        width: 100%;
        height: 90vh;
      }
      
      .login_form {
        width: 50%;
        height: 100%;
        padding: 20px;
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
        gap: 30px;
      }
      
      .login_form_body {
        display: flex;
        justify-content: center;
        align-items: center;
        gap: 35px;
        flex-direction: column;
        width: 100%;
      }
      
      .login_form_body #id_email,
      .login_form_body #id_password {
        width: 300px;
        padding: 10px;
        border-radius: 5px;
        border: 1px solid #ccc;
      }
      
      /* .login_form_body input[type="submit"] {
          background-color: #2E6D9E;
          color: white;
          border: none;
          padding: 10px;
          cursor: pointer;
          width: 50%;
          border-radius: 50px;
      }
      
      .login_form_body input[type="submit"]:hover {
          transition: 0.3s;
          background-color: #4E2498;
      } */
      
      .register_form {
        width: 50%;
        height: 100%;
        padding: 60px;
        padding-left: 150px;
      
        display: flex;
        justify-content: center;
        align-items: center;
        position: relative;
        background-image: url("{% static 'necysc_app/images/king.png'%}");
        background-size: cover;
        background-position: center;
        background-repeat: no-repeat;
        color: white;
        flex-direction: column;
        gap: 50px;
        text-align: center;
        clip-path: polygon(20% 0, 100% 0, 100% 100%, 0% 100%);
      }

      .register_form::before {
        content: '';
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(0, 0, 0, 0.6);
      }
      
      .register_form h2 {
        font-size: 35px;
        z-index: 2;
      }
      
      .register_form p {
        font-size: 15px;
        z-index: 2;
      }
      
      .register_form a {
        border: 1px solid white;
        padding: 10px 20px;
        color: white;
        background-color: transparent;
        text-decoration: none;
        width: 350px;
        font-size: 15px;
        border-radius: 50px;
        transition: background-color 0.3s ease;
        z-index: 2;
      }
      
      .register_form a:hover {
        color: white;
        background-color: rgba(255, 255, 255, 0.3);
        z-index: 2;
      }
</style>
<div class="login_page">
    <!-- Login Form -->
    <div class="login_form">
        <h1>Welcome Back!</h1>
        <form method="POST" action="" class="login_form_body">
            {% csrf_token %}

            <!--name="username" because django authentication by default refers to username-->
            <div>
                <label for="id_email">Email</label>
                <input type="email" name="username" id="id_email" required>
            </div>
            <div>
                <label for="id_password">Password</label>
                <input type="password" name="password" id="id_password" required>
            </div>
            <input style="background-color: #4e598c; color: #f9c784; transition: all 0.3s ease; padding: 10px 20px;
                            border-radius: 20px;
                            display: inline-block;
                            text-align: center;" 
                    class="fw-bold w-50" type="submit" value="Login" name="Login User">
        </form>
        
        {% if form.errors %}
        <div>
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong>Invalid email or password.</strong> Please try again.
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
        </div>
        {% endif %}
    </div>

    <!-- Register Form -->
    <div class="register_form">
        <h2>Don't Have an Account?</h2>
        <p>Sign up for the summer!</p>
        <a class="btn " href="{% url 'necysc_app:register' %}">Sign Up</a>
    </div>
    <script>
        var form_fields = document.getElementsByTagName('input')
        form_fields[1].placeholder = 'Email...';
        form_fields[2].placeholder = 'Enter password...';
        for (var field in form_fields) {
            form_fields[field].className += ' form-control'
        }
    </script>
</div>

{% endblock %}

necysc_app/templates/necysc_app/applicant/read_application.html
{% extends "necysc_app/base.html" %} 

{% block title %} Home {% endblock %} 

{% block content %}
<h1>This application</h1>

<p>Edit / view this application</p>

{% endblock %}

necysc_app/templates/necysc_app/applicant/register.html
{% extends "necysc_app/base.html" %} 

{% load static %}

{% block title %} Register {% endblock %}

{% block content %}

<style>
    /* Register Page Container */
.register_page {
    display: flex;
    justify-content: center;
    align-items: center;
    width: 100%;
    flex-direction: row-reverse;
    height: 90vh;
}

/* Register Form Section */
.register_form {
    width: 50%;
    height: 100%;
    padding-left: 50px;
    display: flex;
    justify-content: center;
    align-items: center;
    flex-direction: column;
    gap: 30px;
}

.register_form h1 {
    font-size: 50px;
}

.register_form_body {
    display: flex;
    justify-content: center;
    align-items: center;
    gap: 35px;
    flex-direction: column;
    width: 100%;
}

.register_form_body #id_username, 
.register_form_body #id_email, 
.register_form_body #id_password1, 
.register_form_body #id_password2 {
    width: 300px;
    padding: 10px;
    border-radius: 5px;
    border: 1px solid #ccc;
}

/* Login Redirect Section with Triangle */
.login_redirect {
    width: 50%;
    height: 100%;
    padding: 60px;
    padding-right: 150px;
    display: flex;
    justify-content: center;
    align-items: center;
    position: relative;
    background-image: url("{% static 'necysc_app/images/night.png' %}");
    background-size: cover;
    background-position: center;
    background-repeat: no-repeat;
    z-index: 1;
    color: white;
    flex-direction: column;
    gap: 50px;
    text-align: center;
    clip-path: polygon(0 0, 80% 0, 100% 100%, 0% 100%); /* Triangle shape */
}

.login_redirect::before {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-color: rgba(0, 0, 0, 0.6);
}

.login_redirect h2 {
    font-size: 35px;
    z-index: 2;
}

.login_redirect p {
    font-size: 15px;
    z-index: 2;
}

.login_redirect a {
    border: 1px solid white;
    padding: 10px 20px;
    color: white;
    background-color: transparent;
    text-decoration: none;
    width: 350px;
    font-size: 15px;
    border-radius: 50px;
    transition: background-color 0.3s ease;
    z-index: 2;
}

.login_redirect a:hover {
    color: white;
    background-color: rgba(255, 255, 255, 0.3);
    z-index: 2;
}

.btn-purple {
    background-color: #4e598c;
    color: #f9c784;
    transition: all 0.3s ease;
    border: none;
    padding: 10px;
    cursor: pointer;
    width: 50%;
    border-radius: 50px;
  }
  
  .btn-purple:hover {
    background-color: #f9c784;
    color: #ffffff;
  }

</style>
<div class="register_page">
    <div class="register_form">
        <h2 style="color: #4e598c">Create Your Account</h2>
        <form method="POST" action="" class="register_form_body">
            {% csrf_token %}
            <div>
                {{ form.username.label }}
                {{ form.username }}
            </div>
            <div>
                {{ form.email.label }}
                {{ form.email }}
            </div>
            <div>
                {{ form.password1.label }}
                {{ form.password1 }}
            </div>
            <div>
                {{ form.password2.label }}
                {{ form.password2 }}
            </div>

            <input type="submit" class="fw-bold btn-purple" value="Register" name="Create User">
        </form>

        {% if form.errors %}
        <div>
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <strong>Invalid email or password confirmation</strong> Please try again.
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
        </div>
        {% endif %}

    </div>
    <div class="login_redirect">
       <h2>Already have an account? </h2> 
       <p>Login to view your application!</p>
        <a href="{% url 'necysc_app:login' %}">Login</a>
    </div>
</div>

<script>
    var form_fields = document.getElementsByTagName('input');
    form_fields[1].placeholder = 'Username...';
    form_fields[2].placeholder = 'Email...';
    form_fields[3].placeholder = 'Enter password...';
    form_fields[4].placeholder = 'Re-enter password...';

    for (var i = 0; i < form_fields.length; i++) {
        form_fields[i].className += ' form-control';
    }
</script>

{% endblock %}