necysc/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path("", include("necysc_app.urls")),
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('images/favicon.ico'))),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
]

necysc_app/urls.py
from django.urls import path

from . import views

app_name = "necysc_app"
urlpatterns = [
    # Website Pages
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("programs/", views.programs, name="programs"),
    path("staff/", views.staff, name="staff"),
    path("faq/", views.faq, name="faq"),
    path("registration/", views.registration, name="registration"),
    path("logout/", views.logout_view, name="logout"),
    path("registrationinfo/", views.registrationinfo, name="registrationinfo"),
    # Applicant Portal Pages
    path("applicant/login/", views.login, name="login"),
    path("applicant/register/", views.register, name="register"),
    path("applicant/", views.home, name="home"),
    path("applicant/new_application/",
         views.new_application, name="new_application"),
    path("applicant/submit_application/",
         views.submit_application, name="submit_application"),
    path("applicant/application_review/<int:application_id>/",
         views.application_detail, name="application_detail"),
    path("applicant/edit_application/<int:application_id>/",
         views.edit_application, name="edit_application"),
]

necysc_app/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms
from django.contrib.auth.models import User
from .models import Applicant

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class CreateAuthenticationForm(AuthenticationForm):    
    class Meta:
        model = User
        fields = ['username', 'password']

class ApplicationForm(forms.ModelForm):
    class Meta:
        model = Applicant
        fields = [# camper info
                  'applicant_fname', 'applicant_lname', 'applicant_chinese_name', 'applicant_email',
                  'applicant_bday', 'applicant_sex', 'applicant_grade', 'applicant_shirt_size', 
                  'program', 
                  'street_address', 'city', 'state', 'zip_code',

                  # parent/guardian/emergency contact info
                  'parent1_fname', 'parent1_lname', 'parent1_relationship', 'parent1_phone', 'parent1_email', 'parent1_for_POD',
                  'parent2_fname', 'parent2_lname', 'parent2_relationship', 'parent2_phone', 'parent2_email', 'parent2_for_POD',
                  'additional_emergency_contact_fname', 'additional_emergency_contact_lname', 'additional_emergency_contact_relationship', 'additional_emergency_contact_phone',

                  # POD preference
                  'interest_in_POD_lead',

                  # roommate requests
                  'preferred_roommate',

                  # medical info
                  'insurance_provider', 'subscriber_name', 'primary_physician_name', 'primary_physician_phone',
                  'grant_hospital_permission', 'grant_medical_treatment_permission', 'grant_first_aid_permission', 'grant_meds_permission', 'grant_bug_spray_permission', 'grant_skin_treatment_permission',
                  'allergies', 'allergies_description', 'initial_for_allergy_treatment', 'epi_pen_prescribed',
                  'social_emotional_concerns',
                  'wear_glasses', 'wear_contacts', 'wear_hearing_aids',
                  'medication', 'medication_description', 
                  'opt_out_activities', 'medical_comments',
                  'signature',

                  # pickup info
                  'allowed_pickup_persons', 'available_for_carpool', 

                  # payment info
                  'payment_camp', 'payment_pod', 'payment_donation', 'payment_total', 'financial_aid_requested',
                  
                  # additional info
                  'listing_on_weekbook', 'camper_contact_email', 
                  'interest_in_committee', 'interest_in_wkbook_ads',
                  'referrals', 'heard_from',
                
                  # important docs
                  'camp_rule_agreement', 'liability_agreement',
                  ]

necysc_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from .models import Applicant, GlobalData
from .forms import CreateAuthenticationForm, CreateUserForm, ApplicationForm
from django.contrib.auth import login as auth_login, authenticate, logout
from django.contrib.auth.decorators import login_required

# Website Pages


def index(request):
    context = {}
    return render(request, 'necysc_app/website/index.html', context)


def about(request):
    context = {}
    return render(request, 'necysc_app/website/about.html', context)


def programs(request):
    context = {}
    return render(request, 'necysc_app/website/programs.html', context)


def staff(request):
    context = {}
    globaldata = GlobalData.get_solo()
    context = {
        "globaldata": globaldata,
    }
    print(globaldata)
    return render(request, 'necysc_app/website/staff.html', context)


def registration(request):
    context = {}
    return render(request, 'necysc_app/website/registration.html', context)


def faq(request):
    context = {}
    return render(request, 'necysc_app/website/faq.html', context)


def registrationinfo(request):
    context = {}
    return render(request, 'necysc_app/website/registration.html', context)

# Applicant Portal


def login(request):
    # check if user is already logged in
    if request.user.is_authenticated:
        return redirect('necysc_app:home')
    if request.method == 'POST':
        form = CreateAuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                auth_login(request, user)
                return redirect('necysc_app:home')
    else:
        form = CreateAuthenticationForm()
    context = {'form': form}
    return render(request, 'necysc_app/applicant/login.html', context)


def register(request):
    # check if user is already logged in
    if request.user.is_authenticated:
        return redirect('necysc_app:home')

    form = CreateUserForm()
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password1')
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            # fix
            return redirect('necysc_app:login')
    context = {'form': form}
    return render(request, 'necysc_app/applicant/register.html', context)


@login_required
def logout_view(request):
    logout(request)
    return redirect('necysc_app:index')


@login_required
def home(request):
    applications = Applicant.objects.filter(user=request.user)

    context = {'applications': applications}
    return render(request, 'necysc_app/applicant/index.html', context)

# show each application


@login_required
def application_detail(request, application_id):
    application = Applicant.objects.get(id=application_id)
    context = {'application': application}
    if application.user == request.user:
        return render(request, 'necysc_app/applicant/application_detail.html', context)
    else:
        return redirect('necysc_app:home')


@login_required
def edit_application(request, application_id):
    application = Applicant.objects.get(id=application_id, user=request.user)
    if not application.user == request.user:
        return redirect('necysc_app:home')
    if request.method == 'POST':
        form = ApplicationForm(request.POST, instance=application)
        if form.is_valid():
            form.save()
            return redirect('necysc_app:application_detail', application_id=application.id)
    else:
        form = ApplicationForm(instance=application)
    context = {'form': form, 'application': application}
    return render(request, 'necysc_app/applicant/edit_application.html', context)


@login_required
def new_application(request):
    form = ApplicationForm()

    globaldata = GlobalData.get_solo()

    context = {
        "form": form,
        "globaldata": globaldata,
    }
    return render(request, 'necysc_app/applicant/new_application.html', context)


@login_required
def submit_application(request):
    if request.method == 'POST':
        form = ApplicationForm(request.POST)
        if form.is_valid():
            # Create instance but don't save yet
            application = form.save(commit=False)
            # check if application exists
            application.user = request.user        # Assign the current user
            application.save()                     # Now save the instance
            form.save()
            return redirect('necysc_app:home')
    else:
        redirect('necysc_app:new_application')
    context = {"form": form}
    return render(request, 'necysc_app/applicant/submit_application.html', context)

necysc_app/templates/necysc_app/website/index.html
{% extends "necysc_app/base.html" %} {% load static %}

{% block title %} Home {% endblock %} 

{% block content %}

<link rel="stylesheet" href="{% static 'necysc_app/index.css' %}">
<style>
.hero-section { 
    background-image: url("{% static 'necysc_app/images/home_hero_banner.gif' %}");
}

.hero-section::before {
    content: "";
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-color: rgba(0, 0, 0, 0.3); /* Adjust the opacity as needed */
    z-index: 1;
    transition: background-color 0.3s ease;
}

.hero-section:hover::before {
    background-color: rgba(0, 0, 0, 0.8); /* Adjust the opacity as needed */
}

@media (max-width: 776px) {
    .ratio {
        width: 47% !important; /* Adjust the value as needed */
    }
}

.bg-purple {
    background-color: #4E598C;
}

</style>

<section>
    <div class="hero-section shadow position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
        <div class="col-md-10 p-lg-5 mx-auto my-5 position-relative container">
            <h1 class="display-4 fw-bold text-white" id="importantdates" style="">New England Chinese Youth Summer Camp</h1>
        </div>
    </div>
</section>

<h1 class="ps-5 mb-3 pt-3" id="aboutus">About Us</h1>
<p class="ps-5 pe-5 mb-4 col-md-6">Established in 1986, the New England Chinese Youth Summer Camp (NECYSC) is a non-profit organization 
    run by dedicated parents and volunteers. Hosted at Brandeis University, our week-long summer camp is designed 
    for youth aged 6 to 15. 
    <a class="programslink" href="{% url 'necysc_app:programs' %}" style="color: #f9c784;">A range of programs - including Day, Overnight, and ExplorAsian</a> - are provided, with 
    the primary goal of nurturing cultural appreciation and fostering a strong community spirit.
</p>
<div class="ps-5">
    <a href="{% url 'necysc_app:register' %}" class="col-md-3 btn-purple rounded-pill fw-bold">
        Register today!
    </a>
</div>

{% comment %} <div class="ms-5 me-5 mb-5" style="height: 2px;"></div> {% endcomment %}
<div class="bg-purple position-relative" style="line-height: 0;">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#ffffff" fill-opacity="1" d="M0,96L48,122.7C96,149,192,203,288,202.7C384,203,480,149,576,144C672,139,768,181,864,186.7C960,192,1056,160,1152,144C1248,128,1344,128,1392,128L1440,128L1440,0L1392,0C1344,0,1248,0,1152,0C1056,0,960,0,864,0C768,0,672,0,576,0C480,0,384,0,288,0C192,0,96,0,48,0L0,0Z"></path></svg>
    <h2 class="mb-5 text-white text-center">An authentic <span class="fw-bolder text-decoration-underline" style="text-underline-offset: 10px;">Chinese-American</span> cultural experience...</h2>
    <div class="row ms-md-5 me-md-5 pt-0 justify-content-center align-items-center">
    <div class="ratio ratio-1x1 mb-5 col-3 mx-2 shadow" style="width: 23%">
        <img src="{% static 'necysc_app/images/waterballoons.png' %}" alt="Water Balloons Image" class="img-fluid" style="object-fit: cover;">
    </div>
    <div class="ratio ratio-1x1 mb-5 col-3 mx-2 shadow" style="width: 23%">
        <img src="{% static 'necysc_app/images/indoors.png' %}" alt="Indoors Image" class="img-fluid" style="object-fit: cover;">
    </div>
    <div class="ratio ratio-1x1 mb-5 col-3 mx-2 shadow" style="width: 23%">
        <img src="{% static 'necysc_app/images/pose.png' %}" alt="Pose Image" class="img-fluid" style="object-fit: cover;">
    </div>
    <div class="ratio ratio-1x1 mb-5 col-3 mx-2 shadow" style="width: 23%">
        <img src="{% static 'necysc_app/images/filming.png' %}" alt="Filming Image" class="img-fluid" style="object-fit: cover;">
    </div>
</div>
</div>

<div class="shadow fansparallax mobileparallax"></div>
{% comment %} <div class="ms-5 me-5 mb-5 bg-dark" style="height: 2px;"></div> {% endcomment %}

<div class="bg-purple position-relative pt-5">
<div class="ps-5 pe-5 justify-content-center align-items-center">
    <h2 class="text-center text-white">
        Camp Activities
    </h2>
    <p class="col-md-6 m-auto text-white">Our campers actively participate in cultural activities like Chinese Yo-yo, Kung-fu, 
        and Calligraphy throughout the day. These are complemented by counselor-led events such as 
        Carnival, Fun In The Sun, Talent Show, End-of-the-Week Dance, and the eagerly-awaited CIT Dress Up. 
        Campers create life-long memories and friendships that go beyond the ordinary camp setting. As the week concludes, 
        each group performs skills they learned during their time at NECYSC for friends and family members.
    </p>
    <p class="col-md-8 m-auto text-white text-center pt-4">
        Get a glimpse into camp life through the 
        <a href="https://sites.google.com/necysc.org/times" target="_blank" class="col-md-6 text-white fw-bold text-decoration-underline" style="text-underline-offset: 5px">
            NECYSC Times
        </a>
    </p>
</div>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#ffffff" fill-opacity="1" d="M0,96L48,122.7C96,149,192,203,288,202.7C384,203,480,149,576,144C672,139,768,181,864,186.7C960,192,1056,160,1152,144C1248,128,1344,128,1392,128L1440,128L1440,320L1392,320C1344,320,1248,320,1152,320C1056,320,960,320,864,320C768,320,672,320,576,320C480,320,384,320,288,320C192,320,96,320,48,320L0,320Z"></path></svg>
</div>


<div class="row ms-md-5 me-md-5 mb-5 justify-content-center align-items-center">
    <div class="ratio ratio-1x1 mb-5 mx-2 shadow" style="width: 23%">
        <img src="{% static 'necysc_app/images/lunch.png' %}" alt="Lunch Image" class="img-fluid" style="object-fit: cover;">
    </div>
    <div class="ratio ratio-1x1 mb-5 mx-2 shadow" style="width: 23%">
        <img src="{% static 'necysc_app/images/swim.png' %}" alt="Swim Image" class="img-fluid" style="object-fit: cover;">
    </div>
    <div class="ratio ratio-1x1 mb-5 mx-2 shadow" style="width: 23%">
        <img src="{% static 'necysc_app/images/flags.png' %}" alt="Flags Image" class="img-fluid" style="object-fit: cover;">
    </div>
    <div class="ratio ratio-1x1 mb-5 mx-2 shadow" style="width: 23%">
        <img src="{% static 'necysc_app/images/instrument.png' %}" alt="Instrument Image" class="img-fluid" style="object-fit: cover;">
    </div>
</div>

<div class="shadow volleyballparallax mobileparallax mb-5"></div>

<div class="ms-5 me-5 mb-5 bg-dark" style="height: 2px;"></div>

<div class="container d-flex justify-content-center">
    <div class="card shadow glow h-100 d-flex flex-column" style="max-width: 500px; width: 100%;">
        <div class="card-body">
            <h3 class="card-title">Sample Schedule</h3>
            <!-- Horizontal line -->
            {% comment %} <div class="bg-secondary mt-3 mb-3" style="height: 1px;"></div>
            <h5 class="card-text">Tuesday</h5>
            <p>8:30 - 9:00 - Check-in</p>
            <p>9:25 - 10:25 - Folk Dance</p>
            <p>10:45 - 11:45 - Dough Figures</p>
            <p>11:45 - 1:00 - Lunch</p>
            <p>1:00 - 2:00 - Bead Art</p>
            <p>2:00 - 2:20 - Break</p>
            <p>2:20 - 3:20 - Big Flag Activity</p>
            <p>3:20 - 3:45 - Snack</p>
            <p>3:45 - 4:45 - Intergroup Time</p>
            <p>5:00 - 5:30 - Check-out</p> {% endcomment %}
            <img src="{% static 'necysc_app/images/schedule.svg' %}" alt="Sample Schedule" class="img-fluid">
        </div>
    </div>
</div>



<!--parallax with fan activity image-->
<style>
    .fansparallax {
      background-image: url("{% static 'necysc_app/images/fans.png' %}");
    
      min-height: 500px;
    
      background-attachment: fixed;
      background-position: center;
      background-repeat: no-repeat;
      background-size: cover;
    }

    .volleyballparallax {
      background-image: url("{% static 'necysc_app/images/volleyball.png' %}");
    
      min-height: 500px;
      position: relative;
      background-attachment: fixed;
      background-position: center;
      background-repeat: no-repeat;
      background-size: cover;
    }

    .overlay {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        width: 70%;
        max-width: 600px;
        padding: 33px;
        background-color: rgba(255, 255, 255);
        border: 1px solid black;
        text-align: center;
    }

    /* turn off parallax scrolling for mobile*/
    @media only screen and (max-device-width: 1366px) {
        .mobileparallax {
            background-attachment: scroll;
        }
    }

    .btn-dark:hover {
        background-color: #5a6268;
        color: white;
    }
</style>




{% endblock %}

necysc_app/templates/necysc_app/website/registration.html
<!--this is distinct from register.html-->
{% extends "necysc_app/base.html" %}

{% block title %} Programs {% endblock %}
{% load static %}

{% block content %}
<style>
.hero-section {
    background-image: url("{% static 'necysc_app/images/registration_banner.jpg' %}");
}

.a {
    font-weight: bold;
    text-decoration: none;
    color: black;
}
</style>
<link rel="stylesheet" href="{% static 'necysc_app/registration.css' %}">
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<section>
    <div class="hero-section shadow position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
        <div class="overlay"></div>
        <div class="col-md-6 p-lg-5 mx-auto my-5 position-relative container">
            <h1 class="display-3 fw-bold text-white" id="importantdates">Registration Process</h1>
        </div>
    </div>
</section>

<div class="container-fluid"> 
    <div class="row justify-content-center"> 
        <div class="text-center p-0 mt-3 mb-2"> 
            <div class="px-0 pt-4 pb-0 mt-3 mb-3"> 
                <form id="form"> 
                    <ul id="progressbar"> 
                        <li class="activeprogress" id="jan"> 
                            <strong>Janurary</strong> 
                        </li> 
                        <li id="feb"><strong>February</strong></li> 
                        <li id="mar"><strong>March</strong></li> 
                        <li id="jun"><strong>June</strong></li>
                        <li id="jul"><strong>July</strong></li>
                        <li id="aug"><strong>August</strong></li>
                    </ul> 
                    <div class="mt-4 mb-3 progress shadow"> 
                        <div class="progress-bar"></div> 
                    </div> <br> 
                    <fieldset> 
                        <h2 style="color: #4e598c;">January</h2> 
                        <p><strong>Early January</strong> - CIT, OPs, RA, Counselors 
                                    <a href="{% url 'necysc_app:staff' %}">application</a> begins</p>
                        <input type="button" name="next-step"
                            class="next-step rounded-pill" value="Next" /> 
                    </fieldset> 
                    <fieldset> 
                        <h2 style="color: #4e598c;">Feburary</h2> 
                        <p><strong>End of February</strong> - All staff applications due</p>
                        <p><strong>Mid-February</strong>- Camper (Day/ON/EA) <a href="{% url 'necysc_app:registration' %}">registration</a> begins + Early Bird discount</p>
                        <input type="button" name="next-step"
                            class="next-step rounded-pill" value="Next" /> 
                        <input type="button" name="previous-step"
                            class="previous-step rounded-pill"
                            value="Previous" /> 
                    </fieldset> 
                    <fieldset> 
                        <h2 style="color: #4e598c;">March</h2> 
                        <p><strong>Mid-March</strong>- Camper (Day/ON/EA) Early Bird discount ends</p>
                        <input type="button" name="next-step"
                            class="next-step rounded-pill" value="Next" /> 
                        <input type="button" name="previous-step"
                            class="previous-step rounded-pill"
                            value="Previous" /> 
                    </fieldset> 
                    <fieldset> 
                        <h2 style="color: #4e598c;">June</h2> 
                        <p><strong>Mid-June</strong> - Overnight and EA camper <a href="{% url 'necysc_app:registration' %}">registration</a> due</p>
                        <p><strong>End of June</strong> - Day camper <a href="{% url 'necysc_app:registration' %}">registration</a> due</p>
                        <input type="button" name="next-step"
                            class="next-step rounded-pill" value="Next" /> 
                        <input type="button" name="previous-step"
                            class="previous-step rounded-pill"
                            value="Previous" /> 
                    </fieldset> 
                    <fieldset> 
                        <h2 style="color: #4e598c;">July</h2> 
                        <p><strong>Mid-July</strong> - Final Camp information package email to accepted campers</p>
                        <p><strong>End Of July</strong> - Overnight and ExplorAsian camper check-in</p>
                        <p><strong>End of July</strong> - Day camper check-in</p>
                        <input type="button" name="next-step"
                            class="next-step rounded-pill" value="Next" /> 
                        <input type="button" name="previous-step"
                            class="previous-step rounded-pill"
                            value="Previous" /> 
                    </fieldset> 
                    <fieldset> 
                        <h2 style="color: #4e598c;">August</h2>
                        <p><strong>Begining of August</strong> - Day camper program ends</p>
                        <p><strong>Begining of August</strong> - Overnight and ExplorAsian camper program ends</p>
                        <input type="button" name="previous-step"
                            class="previous-step rounded-pill"
                            value="Previous" /> 
                    </fieldset> 
                </form> 
            </div> 
            <div class="bg-dark mt-5 mb-5 m-4" style="height: 2px;"></div>
        </div> 
    </div> 
</div>
    
<section>
    <div class="container">
        <h2 id="financialaid" style="color: #4e598c;" class="mb-3">Financial Aid</h2>
        <p><strong>We try our best to make our programs affordable for everyone.</strong> Financial Aid is available and is based solely on need. 
            Families who qualify are encouraged to apply as soon as possible. It is essential that you provide support document 
            to demonstrate your need. Our goal is to offer an opportunity to families who may otherwise not be able to 
            afford the program to share our camp experience.
        </p>
        <p>
            The Financial Aid application is strictly confidential. Financial Aid is a separate process from program acceptance 
            and is awarded after program acceptance. Please complete both the Camper/CIT program 
            <a href="https://www.necysc.org/v2/files/Financial_Aid_form.pdf" target="_blank">application form</a> (indicating 
            that you are applying for Financial Aid) and the Financial Aid application form. Please also note that it is 
            required that you send in a 50% deposit with your financial application.
        </p>
        <p>
            Our data is based on the Federal Poverty Guidelines, which are released each year.
        </p>
        <p>
            Please mail the following documents to NECYSC, P.O. Box 615, Weston, MA, 02493 or email to <a href="mailto:registration@necysc.org">registration@necysc.org</a>.
        </p>
        <p>
            Required documents for verification of income with rest of registration forms (Submit at Time of Registration 
            or Before May 1, 2024):
        </p>
        <ul>
            <li>Financial Aid Application Form</li>
            <li>2022 family tax return copy (IRS 1040 form)</li>
            <li>Exemption approval of the School Lunch Program, or other relevant documents</li>
            <li>Cover letter explaining your situation.</li>
        </ul>
    </div>
</section>
    <script>
    $(document).ready(function () { 
        var currentGfgStep, nextGfgStep, previousGfgStep; 
        var opacity; 
        var current = 1; 
        var steps = $("fieldset").length; 

        setProgressBar(current); 

        $(".next-step").click(function () { 

            currentGfgStep = $(this).parent(); 
            nextGfgStep = $(this).parent().next(); 

            $("#progressbar li").eq($("fieldset") 
                .index(nextGfgStep)).addClass("activeprogress"); 

            nextGfgStep.show(); 
            currentGfgStep.animate({ opacity: 0 }, { 
                step: function (now) { 
                    opacity = 1 - now; 

                    currentGfgStep.css({ 
                        'display': 'none', 
                        'position': 'relative'
                    }); 
                    nextGfgStep.css({ 'opacity': opacity }); 
                }, 
                duration: 500 
            }); 
            setProgressBar(++current); 
        }); 

        $(".previous-step").click(function () { 

            currentGfgStep = $(this).parent(); 
            previousGfgStep = $(this).parent().prev(); 

            $("#progressbar li").eq($("fieldset") 
                .index(currentGfgStep)).removeClass("activeprogress"); 

            previousGfgStep.show(); 

            currentGfgStep.animate({ opacity: 0 }, { 
                step: function (now) { 
                    opacity = 1 - now; 

                    currentGfgStep.css({ 
                        'display': 'none', 
                        'position': 'relative'
                    }); 
                    previousGfgStep.css({ 'opacity': opacity }); 
                }, 
                duration: 500 
            }); 
            setProgressBar(--current); 
        }); 

        function setProgressBar(currentStep) { 
            var percent = parseFloat(100 / steps) * current; 
            percent = percent.toFixed(); 
            $(".progress-bar") 
                .css("width", percent + "%") 
        } 

        $(".submit").click(function () { 
            return false; 
        }) 
    }); 
</script> 

{% endblock %}