necysc/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path("", include("necysc_app.urls")),
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('images/favicon.ico'))),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
]

necysc_app/urls.py
from django.urls import path

from . import views

app_name = "necysc_app"
urlpatterns = [
    # Website Pages
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("programs/", views.programs, name="programs"),
    path("staff/", views.staff, name="staff"),
    path("faq/", views.faq, name="faq"),
    path("registration/", views.registration, name="registration"),
    path("logout/", views.logout_view, name="logout"),
    path("registrationinfo/", views.registrationinfo, name="registrationinfo"),
    # Applicant Portal Pages
    path("applicant/login/", views.login, name="login"),
    path("applicant/register/", views.register, name="register"),
    path("applicant/", views.home, name="home"),
    path("applicant/new_application/",
         views.new_application, name="new_application"),
    path("applicant/submit_application/",
         views.submit_application, name="submit_application"),
    path("applicant/application_review/<int:application_id>/",
         views.application_detail, name="application_detail"),
    path("applicant/edit_application/<int:application_id>/",
         views.edit_application, name="edit_application"),
]

necysc_app/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms
from django.contrib.auth.models import User
from .models import Applicant

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class CreateAuthenticationForm(AuthenticationForm):    
    class Meta:
        model = User
        fields = ['username', 'password']

class ApplicationForm(forms.ModelForm):
    class Meta:
        model = Applicant
        fields = [# camper info
                  'applicant_fname', 'applicant_lname', 'applicant_chinese_name', 'applicant_email',
                  'applicant_bday', 'applicant_sex', 'applicant_grade', 'applicant_shirt_size', 
                  'program', 
                  'street_address', 'city', 'state', 'zip_code',

                  # parent/guardian/emergency contact info
                  'parent1_fname', 'parent1_lname', 'parent1_relationship', 'parent1_phone', 'parent1_email', 'parent1_for_POD',
                  'parent2_fname', 'parent2_lname', 'parent2_relationship', 'parent2_phone', 'parent2_email', 'parent2_for_POD',
                  'additional_emergency_contact_fname', 'additional_emergency_contact_lname', 'additional_emergency_contact_relationship', 'additional_emergency_contact_phone',

                  # POD preference
                  'interest_in_POD_lead',

                  # roommate requests
                  'preferred_roommate',

                  # medical info
                  'insurance_provider', 'subscriber_name', 'primary_physician_name', 'primary_physician_phone',
                  'grant_hospital_permission', 'grant_medical_treatment_permission', 'grant_first_aid_permission', 'grant_meds_permission', 'grant_bug_spray_permission', 'grant_skin_treatment_permission',
                  'allergies', 'allergies_description', 'initial_for_allergy_treatment', 'epi_pen_prescribed',
                  'social_emotional_concerns',
                  'wear_glasses', 'wear_contacts', 'wear_hearing_aids',
                  'medication', 'medication_description', 
                  'opt_out_activities', 'medical_comments',
                  'signature',

                  # pickup info
                  'allowed_pickup_persons', 'available_for_carpool', 

                  # payment info
                  'payment_camp', 'payment_pod', 'payment_donation', 'payment_total', 'financial_aid_requested',
                  
                  # additional info
                  'listing_on_weekbook', 'camper_contact_email', 
                  'interest_in_committee', 'interest_in_wkbook_ads',
                  'referrals', 'heard_from',
                
                  # important docs
                  'camp_rule_agreement', 'liability_agreement',
                  ]

necysc_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from .models import Applicant, GlobalData
from .forms import CreateAuthenticationForm, CreateUserForm, ApplicationForm
from django.contrib.auth import login as auth_login, authenticate, logout
from django.contrib.auth.decorators import login_required

# Website Pages


def index(request):
    context = {}
    return render(request, 'necysc_app/website/index.html', context)


def about(request):
    context = {}
    return render(request, 'necysc_app/website/about.html', context)


def programs(request):
    context = {}
    return render(request, 'necysc_app/website/programs.html', context)


def staff(request):
    context = {}
    globaldata = GlobalData.get_solo()
    context = {
        "globaldata": globaldata,
    }
    print(globaldata)
    return render(request, 'necysc_app/website/staff.html', context)


def registration(request):
    context = {}
    return render(request, 'necysc_app/website/registration.html', context)


def faq(request):
    context = {}
    return render(request, 'necysc_app/website/faq.html', context)


def registrationinfo(request):
    context = {}
    return render(request, 'necysc_app/website/registration.html', context)

# Applicant Portal


def login(request):
    # check if user is already logged in
    if request.user.is_authenticated:
        return redirect('necysc_app:home')
    if request.method == 'POST':
        form = CreateAuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                auth_login(request, user)
                return redirect('necysc_app:home')
    else:
        form = CreateAuthenticationForm()
    context = {'form': form}
    return render(request, 'necysc_app/applicant/login.html', context)


def register(request):
    # check if user is already logged in
    if request.user.is_authenticated:
        return redirect('necysc_app:home')

    form = CreateUserForm()
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password1')
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            # fix
            return redirect('necysc_app:login')
    context = {'form': form}
    return render(request, 'necysc_app/applicant/register.html', context)


@login_required
def logout_view(request):
    logout(request)
    return redirect('necysc_app:index')


@login_required
def home(request):
    applications = Applicant.objects.filter(user=request.user)

    context = {'applications': applications}
    return render(request, 'necysc_app/applicant/index.html', context)

# show each application


@login_required
def application_detail(request, application_id):
    application = Applicant.objects.get(id=application_id)
    context = {'application': application}
    if application.user == request.user:
        return render(request, 'necysc_app/applicant/application_detail.html', context)
    else:
        return redirect('necysc_app:home')


@login_required
def edit_application(request, application_id):
    application = Applicant.objects.get(id=application_id, user=request.user)
    if not application.user == request.user:
        return redirect('necysc_app:home')
    if request.method == 'POST':
        form = ApplicationForm(request.POST, instance=application)
        if form.is_valid():
            form.save()
            return redirect('necysc_app:application_detail', application_id=application.id)
    else:
        form = ApplicationForm(instance=application)
    context = {'form': form, 'application': application}
    return render(request, 'necysc_app/applicant/edit_application.html', context)


@login_required
def new_application(request):
    form = ApplicationForm()

    globaldata = GlobalData.get_solo()

    context = {
        "form": form,
        "globaldata": globaldata,
    }
    return render(request, 'necysc_app/applicant/new_application.html', context)


@login_required
def submit_application(request):
    if request.method == 'POST':
        form = ApplicationForm(request.POST)
        if form.is_valid():
            # Create instance but don't save yet
            application = form.save(commit=False)
            # check if application exists
            application.user = request.user        # Assign the current user
            application.save()                     # Now save the instance
            form.save()
            return redirect('necysc_app:home')
    else:
        redirect('necysc_app:new_application')
    context = {"form": form}
    return render(request, 'necysc_app/applicant/submit_application.html', context)

necysc_app/templates/necysc_app/base.html
<!DOCTYPE html>
<html lang="en">
	<!-- Header -->
	{% load static %} {% include 'necysc_app/header.html' %}

	<head>
		<!-- Required meta tags -->
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />

		<!--Bootstrap CSS-->
		<link
			href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
			rel="stylesheet"
			integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
			crossorigin="anonymous"
		/>

		<title>{% block title %} {% endblock %}</title>
		<link rel="preconnect" href="https://fonts.googleapis.com" />
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
		<link
			href="https://fonts.googleapis.com/css2?family=Roboto+Mono:ital,wght@0,100..700;1,100..700&display=swap"
			rel="stylesheet"
		/>

		<!--global Hind font-->
		<link
			href="https://fonts.googleapis.com/css2?family=Hind:wght@400;500;600&display=swap"
			rel="stylesheet"
		/>
		<style>
			body {
				font-family: "Hind", sans-serif;
			}
		</style>

	</head>

	<body>
		<!-- Navbar -->
		{% include 'necysc_app/navbar.html' %}

		<!-- Content -->
		<div class="container">{% block content %} {% endblock %}</div>

		<!-- Footer -->
		{% include 'necysc_app/footer.html' %}

		<!--Bootstrap JavaScript Plugins-->
		<script
			src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
			integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
			crossorigin="anonymous"
		></script>
	</body>
</html>

necysc_app/templates/necysc_app/footer.html
<!-- Footer -->
<footer class="container p-4 m-auto align-items-center justify-content-center" id="contact">
  <div class="ms-5 me-5 mb-5 bg-dark" style="height: 2px;"></div>

  <h2 class="mb-3 mt-5 text-center" style="color: #4e598c;">Connect With Us!</h2>
  <p class="text-center text-muted small"> General Inquiries:
    <a href="mailto:registration@necysc.org" style="color: black">registration@necysc.org</a>
  </p>
  <p class="text-center small text-muted"> Director:
    <a href="mailto:registration@necysc.org" style="color: black">director@necysc.org</a>
  </p>

  <div class="row text-center align-items-center justify-content-center">
    <div class="col-auto">
        <a href="https://www.instagram.com/NECYSC/" style="display: inline-block;" target="_blank">
            <img src="https://cdn.freebiesupply.com/images/large/2x/instagram-icon-white-on-black.png" alt="Instagram Logo" style="width: 50px; height: auto;">
        </a>
    </div>
    <div class="col-auto">
      <a href="https://www.facebook.com/NECYSC" style="display: inline-block;" target="_blank">
          <img src="https://www.freepnglogos.com/uploads/logo-facebook-png/logo-facebook-facebook-logo-png-transparent-svg-vector-bie-supply-18.png" alt="Facebook Logo" style="width: 40px; height: auto;">
      </a>
    </div>
  </div>


  <!-- Copyright -->
  <div class="container"></div>
  <div class="text-center p-4">
    © 2024 Copyright.
    <a class="text-reset" href="https://necysc.org/">necysc.org</a>
  </div>

</footer>
<!-- Footer -->

necysc_app/templates/necysc_app/header.html
<!-- Header -->
<head>
    <meta charset="UTF-8" />
    <!-- Bootstrap Imports -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css"
      rel="stylesheet"
    />
    <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"
    ></script>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    {% load static %}
    <link href="{% static 'necysc_app/style.css' %}" rel="stylesheet" />
    <link rel="icon" href="{%  static 'necysc_app/images/favicon.ico' %}">
</head>

necysc_app/templates/necysc_app/navbar.html
{% load static %}

    <style>
        a {
            font-weight: bold;
            text-decoration: none;
        }

        .dropdown {
            position: relative;
            display: inline-block;
        }

        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #f9f9f9;
            min-width: 160px;
            box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);
            z-index: 10;
            top: 100%;
        }

        .dropdown-content a {
            color: #4e598c;
            padding: 12px 16px;
            text-decoration: none;
            display: block;
            transition: color 0.3s ease, background-color 0.3s ease;
        }

        .dropdown-content a:hover {
            background-color: #4e598c;
            color: #F9C784;
        }

        .dropdown:hover .dropdown-content {
            display: block;
        }

        .navbar-link {
            color: #4e598c;
            transition: color 0.3s ease;
        }

        .navbar-link:hover {
            color: #F9C784;
            background: #4e598c;
            transition: color 0.3s ease;
            padding: 10px 20px;
            border-radius: 9px;
        }

        .active {
            color: #F9C784; 
            background: #4e598c;
            padding: 10px 20px;
            text-decoration: none;
            border-radius: 9px;
        }


        .btn-login {
            background-color: #4e598c;
            color: #F9C784;
            transition: all 0.3s ease;
            padding: 10px 20px;
            border-radius: 20px;
            display: inline-block;
            text-align: center;
        }

        .btn-login:hover {
            background-color: #F9C784;
            color: #FFFFFF;
        }

        .btn-padding {
            padding: 10px 15px;
            border-radius: 20px;
            display: inline-block;
            text-align: center;
            background: #F9C784;
            color: #4e598c;
            transition: all 0.3s ease;
        }

        .btn-padding:hover {
            background-color: #4e598c;
            color: #ffffff;
        }


        .col-auto {
            display: flex;
            align-items: center;
        }

        img {
            height: 4rem;
            max-width: 100%;
        }

        #logobutton {
            background-color: #4e598c;
            transition: all 0.3s ease;
        }

        #logobutton:hover {
            background-color: #F9C784;
            color: #FFFFFF;
        }


        .menu-toggle {
            display: none;
        }
        
        .hamburger {
            display: none;
            font-size: 24px;
            cursor: pointer;
            color: #4e598c;
        }
        
        .nav-links {
            display: flex;
            gap: 15px;
        }
        
        @media (max-width: 1000px) {
            .nav-links {
                display: none;
                flex-direction: column;
                background-color: white;
                position: absolute;
                top: 60px;
                right: 0;
                width: 100%;
                padding: 10px;
                z-index: 1000;
                padding-left: 50px;
                font-size: 3vh;
                padding-right: 50px;
            }
        
            .menu-toggle:checked + .hamburger + .nav-links {
            display: flex;
            }
        
            .hamburger {
            display: block;
            }
        }
        
        .optional {
            color: gray;
            font-style: italic;
        }
        
        .white-link {
            color: #ffffff;
            text-decoration: none;
            transition: color 0.3s ease;
        }
        
        .white-link:hover {
            color: #cccccc;
        }
        
        .welcome-title {
            color: white;
        }
  </style>

<!-- navbar sticky -->
<div class="row mt-2 pt-4 pb-4 mb-3 d-flex ps-4 pe-5 align-items-center gap-3 sticky-top bg-bi-white bg-white row">
    <!-- NECYSC logo -->
    <input type="checkbox" id="menu-toggle" class="menu-toggle">
    <label for="menu-toggle" class="hamburger">
        &#9776;
    </label>

    <div class="nav-links">
       
        <div class="col-auto d-none d-xl-block">
            <a href="{% url 'necysc_app:index' %}" id="logo-link">
                <img src="{% static 'necysc_app/images/logo2.png' %}" alt="Your Image Description" id="logobutton" class="rounded-pill p-2" style="width: 6rem; height: auto"/>
            </a>
        </div>

        <div class="dropdown col-auto">
            {% if request.user.is_authenticated %}
            <a href="{% url 'necysc_app:home' %}" class="navbar-link {% if request.path == '/' %}active{% endif %}">Applicant Home</a>
            {% else %}
            <a href="{% url 'necysc_app:index' %}" class="navbar-link {% if request.path == '/' %}active{% endif %}">Home</a>
            {% endif %}
        </div>

    {% if not request.user.is_authenticated %}
    <div class="dropdown col-auto">
        <a href="{% url 'necysc_app:about' %}" class="navbar-link {% if request.path == '/about/' %}active{% endif %}">About</a>
        <div class="dropdown-content">
            <a href="{% url 'necysc_app:about' %}#sponsors">Sponsors</a>
            <a href="{% url 'necysc_app:about' %}#contact">Contact Us</a>
        </div>
    </div>

    <div class="dropdown col-auto">
        <a href="{% url 'necysc_app:programs' %}" class="navbar-link {% if request.path == '/programs/' %}active{% endif %}">Programs</a>
        <div class="dropdown-content">
            <a href="{% url 'necysc_app:programs' %}#day">Day Camp</a>
            <a href="{% url 'necysc_app:programs' %}#on">Overnight Camp</a>
            <a href="{% url 'necysc_app:programs' %}#ea">ExplorAsian</a>
        </div>
    </div>

    <div class="dropdown col-auto">
        <a href="{% url 'necysc_app:staff' %}" class="navbar-link {% if request.path == '/staff/' %}active{% endif %}">Staff</a>
        <div class="dropdown-content">
            <a href="{% url 'necysc_app:staff' %}#cit">CIT</a>
            <a href="{% url 'necysc_app:staff' %}#counselor">Counselor</a>
            <a href="{% url 'necysc_app:staff' %}#ra">RA</a>
            <a href="{% url 'necysc_app:staff' %}#ops">OPs</a>
            <a href="{% url 'necysc_app:staff' %}#committee">Committee</a>
        </div>
    </div>

    <div class="dropdown col-auto">
        <a href="{% url 'necysc_app:registration' %}" class="navbar-link {% if request.path == '/registration/' %}active{% endif %}">Registration</a>
        <div class="dropdown-content">
            <a href="{% url 'necysc_app:registration' %}#importantdates">2025 Important Dates</a>
            <a href="{% url 'necysc_app:registration' %}#financialaid">Financial Aid</a>
        </div>
    </div>

    <div class="dropdown col-auto">
        <a href="{% url 'necysc_app:faq' %}" class="navbar-link {% if request.path == '/faq/' %}active{% endif %}">FAQ</a>
        <div class="dropdown-content">
            <a href="{% url 'necysc_app:faq' %}#faqregistration">Registration</a>
            <a href="{% url 'necysc_app:faq' %}#faqleavingcamp">Leaves and Visits</a>
            <a href="{% url 'necysc_app:faq' %}#faqhealth">Health and Safety</a>
            <a href="{% url 'necysc_app:faq' %}#camp">Camp Activities</a>
        </div>
    </div>
    {% endif %}
    
    <div class="col-auto ms-auto">
          <a href="https://youtu.be/PPZ1zu8fGl0?si=h436QWcB9vHQeV_G" target="_blank" class="btn-padding me-3">2024 Video</a>
          {% if request.user.is_authenticated %}
          <a href="{% url 'necysc_app:logout' %}" class="btn-login">Logout</a>
          {% else %}
          <a href="{% url 'necysc_app:login' %}" class="btn-login">Login/Register</a>
          {% endif %}
    </div>
    
</div>